### ISSUE TITLE
Create a "BusinessService": cleanly specify the grouping of derivations

### ISSUE THREAD

**Issue by NRBPerdijk** [scala-rules/scala-rules#82]
A BusinessService is another way to specify which parts of a derivation or group of derivations to expose and how. It should:
- help enforce that certain facts are given as input, or no calculation will run,
- allow for optional facts and their defaults to be clearly specified,
- specify outputs,
- ~~hide internally used intermediary result-facts unless specifically requested (debug),~~
- specify which berekeningen/derivations are in scope,
- specify which glossaries are in scope.

**Comment by jhkuperus** [comment]
Some points from our discussion on this topic:

* a `BusinessService` is mainly a  description of a service
* it contains functions to facilitate running the derivations. Calling these will enforce the constraints specified within the service. These are meant to prevent people from circumventing such constraints.
* the run functions are generic in the actual runner (you can specify any `FactEngine` run strategy)
* no filtering is applied to the output, since the concept lives within Scala-Rules, where we always return *all* available information

This means that filtering of outputs is left to any outer layers (e.g. rule-rest). I've changed your initial issue description to reflect this change (strikethrough on one bullet).
